version: "3.7"
services:
  server:
    image: "gyulbe/blog-server:latest"
    build: .
    container_name: blog-server
    restart: unless-stopped
    volumes:
      - appdata:/app
    networks:
      - app
    ports:
      - "8080:8080"